name: exambro
description: "CBT Exam Browser - MTs Nurul Falah"
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # WebView
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.7.0

  # HTTP & Info
  http: ^1.2.1
  package_info_plus: ^9.0.0
  device_info_plus: ^10.1.0

  # Kamera & Face Detection
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.0

  # File & Install
  open_file: ^3.3.2
  path_provider: ^2.1.3
  path: ^1.9.0

  # Permissions
  permission_handler: ^11.3.1

  # URL Launcher (opsional, jika dibutuhkan)
  url_launcher: ^6.2.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_sekolah.png
